groups:
- name: Down
  rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: 'critical'
        annotations:
        summary: "Instance (instance {{ $labels.instance }}) is down"
        description: " (instance {{ $labels.instance }})  has been down for: more than 1 minute."